# Generated by Django 3.0.6 on 2020-07-03 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('Id_Atleta', models.IntegerField(primary_key=True, serialize=False)),
                ('Num_Matri', models.IntegerField(blank=True, null=True, verbose_name='Numero Matricula')),
                ('Nom', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Ape', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('Dire', models.CharField(max_length=60, verbose_name='Direccion')),
                ('Pobla', models.CharField(max_length=50, verbose_name='Poblacion')),
                ('Cod_Pos', models.CharField(max_length=5, verbose_name='Cod. Postal')),
                ('Tel', models.CharField(max_length=9, verbose_name='Telefono')),
                ('Fecha_Nac', models.DateField(verbose_name='Fecha Nacimiento')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_Cat', models.IntegerField(primary_key=True, serialize=False)),
                ('Modalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('Id_Prueba', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom_Prueba', models.CharField(max_length=50, verbose_name='Nom. Prueba')),
                ('Localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('Fecha_Pr', models.DateField(verbose_name='Fecha')),
                ('Fecha_Inicio', models.DateField(verbose_name='Inscripcion Desde')),
                ('Fecha_Fin', models.DateField(verbose_name='Inscripcion Hasta')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('Id_Ins', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_Atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_atletas.Atleta')),
                ('Id_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_atletas.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='Id_Prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_atletas.Prueba'),
        ),
    ]
