# Generated by Django 3.0.6 on 2020-09-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_atletas', '0004_auto_20200807_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='Id_Prueba',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion_atletas.Prueba'),
            preserve_default=False,
        ),
    ]
