# Generated by Django 3.0.6 on 2020-10-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_atletas', '0005_inscripcion_id_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='Num_Matri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Matricula'),
        ),
    ]
